
spring:
  application:
    name: AlzAssistant
    # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alz_assistant
    username: root
    password: hsp
  profiles:
    active: local #??????
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000



server:
  port: 8126
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yzj.alzassistant.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn



